config/routes.rb
Am::Application.routes.draw do

  get "formatvideo/index"
  get "formatvideo/show"
  get "formatvideo/new"
  get "formatvideo/edit"
  get "formatvideo/create"
  get "formatvideo/update"
  get "formatvideo/destroy"

  resources :video_clips

  resources :sessions, :only => [:new, :create, :destroy]
  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :video_clip_steps

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    member { get :download }
  end

  match '/signin',          :to     => 'sessions#new',          :via => 'get'
  match '/sessions',        :to     => 'sessions#create',       :via => 'post'
  match '/signout',         :to     => 'sessions#destroy',      :via => 'delete'

  match '/video_clips_unavailable',   :to => 'video_clips#indexUnavailable',  :via => 'get', :as => :video_clips_unavailables

  root 'sessions#new'

end

app/models/right.rb
class Right < ActiveRecord::Base
    has_and_belongs_to_many :groups, :join_table => 'groups_rights'
    has_and_belongs_to_many :personalgroups, :join_table => 'personal_groupsrights'
end

app/controllers/rights_controller.rb
class RightsController < ApplicationController
  before_filter :verify_access
  before_action :set_right, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_person

  # GET /rights
  # GET /rights.json
  def index
    @rights = Right.all
  end

  # GET /rights/1
  # GET /rights/1.json
  def show
  end

  # GET /rights/new
  def new
    @right = Right.new
  end

  # GET /rights/1/edit
  def edit
  end

  # POST /rights
  # POST /rights.json
  def create
    @right = Right.new(right_params)

    respond_to do |format|
      if @right.save
        format.html { redirect_to @right, notice: 'Right was successfully created.' }
        format.json { render action: 'show', status: :created, location: @right }
      else
        format.html { render action: 'new' }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rights/1
  # PATCH/PUT /rights/1.json
  def update
    respond_to do |format|
      if @right.update(right_params)
        format.html { redirect_to @right, notice: 'Right was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rights/1
  # DELETE /rights/1.json
  def destroy
    @right.destroy
    respond_to do |format|
      format.html { redirect_to rights_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_right
      @right = Right.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def right_params
      params.require(:right).permit(:name, :is_available)
    end

    def verify_access
        if current_person.type != 'Admin'
            respond_to do |format|
                format.html { render :file => "#{Rails.root}/public/422.html", :status => :unprocessable_entity, :layout => false }
            end
        end
    end
end

app/helpers/rights_helper.rb
module RightsHelper
end

app/views/rights/_form.html.erb
<%= form_for(@right) do |f| %>
  <% if @right.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@right.errors.count, "error") %> prohibited this right from being saved:</h2>

      <ul>
      <% @right.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :placeholder => 'Name'  %>
  </div>
  <div class="field">
    <%= f.label :is_available %><br>
    <%= f.check_box :is_available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rights/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Rights <small>Editing right</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Editing right </li>
      </ol>
    </div>
  </div>

  <%= render 'form' %>

  <%= link_to 'Show', @right, class:'btn btn-default' %>
  <%= link_to 'Back', rights_path, class:'btn btn-default' %>
</div>

app/views/rights/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Rights <small>List Rights</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Rights </li>
      </ol>
    </div>
  </div>

  <div>
    <div class="row">
      <div class="col-lg-6">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped tablesorter">
            <thead>
            <tr>
              <th>Name <i class="fa fa-sort"></i></th>
              <th>Is available<i class="fa fa-sort"></i></th>
              <th><i class="fa fa-sort"></i></th>
              <th><i class="fa fa-sort"></i></th>
              <th><i class="fa fa-sort"></i></th>
            </tr>
            </thead>

            <tbody>
            <% @rights.each do |right| %>
                <tr>
                  <td><%= right.name %></td>
                  <td><%= right.is_available %></td>
                  <td><%= link_to 'Show', right %></td>
                  <td><%= link_to 'Edit', edit_right_path(right) %></td>
                  <td><%= link_to 'Destroy', right, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
    <%= link_to 'New Right', new_right_path, class:'btn btn-default' %>
  </div>
  <br>
</div>

app/views/rights/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Rights <small>Create right</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Create right </li>
      </ol>
    </div>
  </div>

  <%= render 'form' %>
  <%= link_to 'Back', rights_path, class:'btn btn-default' %>
</div>

app/views/rights/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Rights <small>Show right</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Show right </li>
      </ol>
    </div>
  </div>

  <p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @right.name %>
  </p>

  <p>
    <strong>Is available:</strong>
    <%= @right.is_available %>
  </p>

  <%= link_to 'Edit', edit_right_path(@right), class:'btn btn-default' %>
  <%= link_to 'Back', rights_path, class:'btn btn-default' %>

</div>