config/routes.rb
Am::Application.routes.draw do

  get "formatvideo/index"
  get "formatvideo/show"
  get "formatvideo/new"
  get "formatvideo/edit"
  get "formatvideo/create"
  get "formatvideo/update"
  get "formatvideo/destroy"

  resources :video_clips

  resources :sessions, :only => [:new, :create, :destroy]
  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :video_clip_steps

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    member { get :download }
  end

  match '/signin',          :to     => 'sessions#new',          :via => 'get'
  match '/sessions',        :to     => 'sessions#create',       :via => 'post'
  match '/signout',         :to     => 'sessions#destroy',      :via => 'delete'

  match '/video_clips_unavailable',   :to => 'video_clips#indexUnavailable',  :via => 'get', :as => :video_clips_unavailables

  root 'sessions#new'

end

app/models/video_clip.rb
#http://thewebfellas.com/blog/2009/8/29/protecting-your-paperclip-downloads
class VideoClip < ActiveRecord::Base
  require 'digest/md5'

  belongs_to :person

  has_many :thumbnails, :dependent => :destroy
  accepts_nested_attributes_for :thumbnails, :allow_destroy => true

  has_many :formatvideos, :dependent => :destroy
  accepts_nested_attributes_for :formatvideos, :allow_destroy => true

  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments, :reject_if => lambda { |attribute| attribute[:message].blank?}, :allow_destroy => true

  has_attached_file :videoitemclip,
                    #:preserve_files => true,
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :bucket => '***************',
                    :s3_host_name => 's3-us-west-2.amazonaws.com',
                    #:default_url => ':class/:attachment/:id/:content_type/:basename.:extension',
                    #:url =>':s3_domain_url',
                    #:s3_permissions => 'authenticated-read',
                    #:s3_protocol => 'http',
                    #:path => ':class/:attachment/:id/:style/:basename.:extension' NORMAL
                    :path => ':class/:attachment/:token/:style/:basename.:extension'


  #acts_as_paranoid

  #validates_attachment_presence :videoitemclip
  #validates_attachment_size :mp3, :less_than => 10.megabytes

  validates :title, presence: true
  validates_presence_of :token


  after_initialize :init, :before_validation_on_create

  validates_attachment_content_type :videoitemclip,
                                    :content_type =>
                                        [ "application/x-mp4",
                                          "video/mpeg",
                                          "video/quicktime",
                                          "video/x-la-asf",
                                          "video/x-ms-asf",
                                          "video/x-msvideo",
                                          "video/x-sgi-movie",
                                          "video/x-flv",
                                          "flv-application/octet-stream",
                                          "video/3gpp",
                                          "video/3gpp2",
                                          "video/3gpp-tt",
                                          "video/BMPEG",
                                          "video/BT656",
                                          "video/CelB",
                                          "video/DV",
                                          "video/H261",
                                          "video/H263",
                                          "video/H263-1998",
                                          "video/H263-2000",
                                          "video/H264",
                                          "video/JPEG",
                                          "video/MJ2",
                                          "video/MP1S",
                                          "video/MP2P",
                                          "video/MP2T",
                                          "video/mp4",
                                          "video/MP4V-ES",
                                          "video/MPV",
                                          "video/mpeg4",
                                          "video/mpeg4-generic",
                                          "video/nv",
                                          "video/parityfec",
                                          "video/pointer",
                                          "video/raw",
                                          "video/rtx"]


  def to_param
    token
  end

  protected

  def before_validation_on_create
    self.token = Digest::MD5.hexdigest(Time.now.strftime("%Y-%d-%m %H:%M:%S %Z").to_s+" "+rand(36**10).to_s(36)) if self.new_record? and self.token.nil?
  end

  private
    #Proteger l'access et mettre la notion du token
    def downloadable?(person)
      person != :person
    end

    def init
      if self.new_record? && self.videoclip_from_url.nil?
        self.is_available = true
      end
    end

    def self.search_video(search_video, current_person)
      if search_video
        where('title LIKE ?', "%#{search_video}%")
      else
        if current_person.type == 'Admin'
          self.all
        else
          where('is_available LIKE ? OR person_id = ?', true, current_person.id)
        end
      end
    end

    def self.search_video_unavailable(search_video_unavailable, current_person)
      if search_video_unavailable
        where('title LIKE ?', "%#{search_video_unavailable}%")
      else
        if current_person.type == 'Admin'
          where('is_available LIKE ?', false)
        end
      end
    end

    def fast_asset=(files)
      if files &&  files.respond_to?('[]')
        files.each do |item|
          self.tmp_upload_dir = "#{item['filepath']}_1"
          tmp_file_path = "#{self.tmp_upload_dir}/#{item['original_name']}"
          FileUtils.mkdir_p(self.tmp_upload_dir)
          FileUtils.mv(item['filepath'], tmp_file_path)

          self.videoitemclip = File.open(tmp_file_path)
=begin
          if file.index(item) == 0
            self.video = File.open(tmp_file_path)
          else
            self.image = File.open(tmp_file_path)
          end
=end
        end
      end
    end
end

app/controllers/video_clips_controller.rb
class VideoClipsController < ApplicationController
  before_action :set_video_clip, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_person

  require 'json'
  require 'open-uri'

  # GET /video_clips
  # GET /video_clips.json
  def index
    #@video_clips = VideoClip.all
    @video_clips  = VideoClip.search_video(params[:search_video], current_person).paginate(:per_page => 10, :page => params[:page])
  end

  def indexUnavailable
    @video_clips_unavailable = VideoClip.search_video_unavailable(params[:search_video_unavailable], current_person).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /video_clips/1
  # GET /video_clips/1.json
  def show
    verify_access_video(@video_clip, 'show')
    @video_clip.increment!(:views)
    @video_clip = VideoClip.find_by_token(params[:id])
    #@video_clip_comments = @video_clip.comments.order("id DESC").paginate(:per_page => 3, :page => params[:page])
    @owner = Person.find_by_id(@video_clip.person_id)
    @new_comment = @video_clip.comments.build

    if @video_clip.videoclip_from_url.empty?
      @file_video = @video_clip.videoitemclip.url
    else
      @file_video = @video_clip.videoclip_from_url
    end

    @thumb_main = nil
    @video_clip.thumbnails.each do |thumbnail|
      if thumbnail.main_thumbnail == true
        @thumb_main = thumbnail
        break
      end
    end
  end

  # GET /video_clips/new
  def new
    verify_access_video(@video_clip, 'new')
    @video_clip = VideoClip.new
    @video_clip.thumbnails.build
  end

  # GET /video_clips/1/edit
  def edit
    verify_access_video(@video_clip, 'edit')
    @video_clip.thumbnails.build
  end

  # POST /video_clips
  # POST /video_clips.json
  def create

    @video_clip = VideoClip.new(video_clip_params)
    thumbnails = Array.new
    @video_clip.views = 0
    @video_clip.person_id = current_person.id

    respond_to do |format|
      if @video_clip.save

        if (@video_clip.videoclip_from_url.empty?)
            filename = @video_clip.videoitemclip_file_name.split('.')[0..-1][0].to_s
            path = @video_clip.videoitemclip.path.to_s
            url = @video_clip.videoitemclip.url
            content = @video_clip.videoitemclip.content_type

            createDirectory(path)
            videoflv = convert_video_to_flv(filename, path, content, url)
            storeFormatOnAmazonS3(@video_clip, videoflv, 'FormatFvl')

            time_video_flv_sec = get_time_flv_in_sec(videoflv, "Duration").gsub(/\n$/,'').to_i
            shift_time = ((time_video_flv_sec*20).to_f/100) #chaque 20% de la video on prend une vignette
            step = 1
            time_tmp = 0

            while time_tmp < time_video_flv_sec
              thumbnail = generate_thumbnail_from_video(filename, videoflv, time_tmp, step)
              thumbnails << thumbnail
              time_tmp += shift_time
              step += 1
            end
            storeThumbnailsOnAmazonS3(thumbnails)

            if @video_clip.videoitemclip.content_type == "video/mp4"
              videoavi = convert_video_to_AVI(filename, path, content, url)
              storeFormatOnAmazonS3(@video_clip, videoavi, 'FormatAvi')

              #videoh264 = convert_video_to_H264(filename, path, content, url)
              #storeFormatOnAmazonS3(@video_clip, videoh264, 'Formath264')
            end

        end
        format.html{ redirect_to video_clip_steps_path(:video_clip_id => @video_clip.id), notice: ' A A' }
        format.json { render action: 'show', status: :created, location: @video_clip }
      else
        format.html { render action: 'new' }
        format.json { render json: @video_clip.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /video_clips/1
  # PATCH/PUT /video_clips/1.json
  def update
    select_thumbnail = 0
    @video_clip.thumbnails.each do |thumbnail|
      if thumbnail.id == params[:main_thumbnail].to_i
        thumbnail.main_thumbnail = true
        select_thumbnail += 1
      else
        thumbnail.main_thumbnail = false
      end
    end

    respond_to do |format|
      if @video_clip.update(video_clip_params) && select_thumbnail == 1
        format.html { redirect_to @video_clip, notice: 'Video clip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_clips/1
  # DELETE /video_clips/1.json
  def destroy
    verify_access_video(@video_clip, 'delete')
    @video_clip.destroy
    respond_to do |format|
      format.html { redirect_to video_clips_url }
      format.json { head :no_content }
    end
  end

  def download
    video_clip = VideoClip.find_by_token(params[:id])
    file_name = nil
    data = nil

    if video_clip.videoclip_from_url.empty?
      video_clip_url = video_clip.videoitemclip.url
      file_name = video_clip.videoitemclip_file_name
      data = open(video_clip_url)
    else
      video_clip_url = video_clip.videoclip_from_url
      file_name = File.basename(URI.parse(video_clip_url).path)
      data = open(video_clip_url)
    end

    send_data data.read, :filename => file_name, :type => data.content_type, :x_sendfile => true
  end


  def download_url
    video_clip = VideoClip.find(params[:id])
    s3 = AWS::S3.new.buckets[ 'aldazjvideo.com' ] # This can be done elsewhere as well.
    s3.url_for( :read,
                expires_in: 60.minutes,
                use_ssl: true,
                response_content_disposition: "attachment; filename='#{video_clip.videoitemclip_file_name}'" ).to_s
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_video_clip
      @video_clip = VideoClip.find_by_token(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_clip_params
      params.require(:video_clip).permit(:title, :description, :is_available, :date, :views, :videoitemclip, :delete_at, :videoclip_from_url,
                                         thumbnails_attributes: [:id, :image, :_destroy, :main_thumbnail],
                                         formatvideos_attributes: [:id, :format, :_destroy],
                                         comments_attributes: [:id, :message, :is_available, :date, :url_for, :_destroy])
    end


    def convert_video_to_flv(filename, path, content, url)
      logger.debug "Convert the video ( #{filename} ) path ( #{path}) from content type of #{content} to flv"
      File.new(File.join(Rails.root, 'public' , 'system', File.dirname(path), "#{filename}.flv"), File::CREAT | File::TRUNC| File::RDWR, 0644)
      videoflv = File.join(Rails.root, 'public' , 'system', File.dirname(path), "#{filename}.flv")
      system("ffmpeg -i #{url} -r 25 -ar 44100 -vcodec flv -ab 32 -y -f flv -s 320x240 #{videoflv}")
      return videoflv
    end

    def convert_video_to_H264(filename, path, content, url)
      logger.debug "Convert the video ( #{filename} ) path ( #{path}) from content type of #{content} to H264"
      File.new(File.join(Rails.root, 'public' , 'system', File.dirname(path), "#{filename}.h264"), File::CREAT | File::TRUNC| File::RDWR, 0644)
      videoh264 = File.join(Rails.root, 'public' , 'system', File.dirname(path), "#{filename}.h264")
      system("ffmpeg -i #{url} -an -vcodec libx264 -crf 23 #{videoh264} -y")
      return videoh264
    end

    def convert_video_to_AVI(filename, path, content, url)
      logger.debug "Convert the video ( #{filename} ) path ( #{path}) from content type of #{content} to H264"
      File.new(File.join(Rails.root, 'public' , 'system', File.dirname(path), "#{filename}.avi"), File::CREAT | File::TRUNC| File::RDWR, 0644)
      videoavi = File.join(Rails.root, 'public' , 'system', File.dirname(path), "#{filename}.avi")
      system("ffmpeg -i #{url} -acodec copy -vcodec copy #{videoavi} -y")
      return videoavi
    end

    def createDirectory(path)
      dir = File.dirname(File.join( Rails.root, 'public' , 'system', path))
      FileUtils.mkdir_p(dir) unless File.directory?(dir)
    end

    def get_time_flv_in_sec(video_flv, duration)
      return `ffmpeg -i #{video_flv} 2>&1 | grep #{duration}| cut -d ' ' -f 4 | sed s/,// | sed 's@\\..*@@g' | awk '{ split($1, A, ":"); split(A[3], B, "."); print 3600*A[1] + 60*A[2] + B[1] }'`
    end

    def generate_thumbnail_from_video(filename, videoflv, time, step)
      logger.debug "Trying to generate screenshots from #{videoflv}"
      asset = File.join(File.dirname(videoflv), "#{filename}_#{step}.jpg")
      system("ffmpeg -ss #{time} -i #{videoflv} -s 320x240 -vframes 1 -f image2 -an #{asset}")
      return asset
    end

    def storeFormatOnAmazonS3(videomp4, videoconverted, format)
      Formatvideo.create({
                             :video_clip_id => videomp4.id,
                             :format =>  File.open(videoconverted),
                             :type => format
                         })
    end

    def storeThumbnailsOnAmazonS3(thumbnails)
      thumbnails.each do |thumb|
        Thumbnail.create({:image => File.open(thumb),
                          :video_clip_id => @video_clip.id,
                          :main_thumbnail => false
                         })
      end
    end

    def verify_access_video(video_clip, current_action)
      case current_action
        when 'show'
          if !(video_clip.is_available?)
            if(current_person.type != 'Admin' && !(current_person_is_video_owner?(video_clip)))
              respond_to do |format|
                format.html { render :file => "#{Rails.root}/public/422.html", :status => :unprocessable_entity, :layout => false }
              end
            end
          end
        when 'edit'
          if(current_person.type != 'Admin' && !(current_person_is_video_owner?(video_clip)))
            respond_to do |format|

app/helpers/video_clips_helper.rb
module VideoClipsHelper

  def thumbnail_selected?(thumbnail)
    @thumbnail = Thumbnail.find(thumbnail)
    return @thumbnail.main_thumbnail
  end

end

app/views/video_clips/_comments.html.erb
<div class="detailBox">
  <div class="commentBox">
    <p class="taskDescription">Comments:</p>
  </div>
  <div class="actionBox">
    <ul class="commentList">
      <% if @video_clip.comments.size != 0 %>
            <% @video_clip.comments.reverse.each  do |comment| %>
                <% if comment.is_available? %>
                  <li>
                    <div class="commentImage">
                      <img src="https://s3-us-west-2.amazonaws.com/aldazjvideo.com/images_extras/user_profil.png" />
                    </div>
                    <div class="commentBox">
                        <div class="commentText">
                          <p class=""> <%= comment.message %> </p> <span class="date sub-text"> <%= comment.created_at %>  </span>
                        </div>
                        <div class="commentOwner">
                          <% if !(comment.person_id.nil?) %>
                              <% owner = Person.find_by_id(comment.person_id)%>
                              <%#= owner.lastname.upcase+' '+owner.firstname %>
                              <%= link_to owner.lastname.upcase+' '+owner.firstname, owner %>
                          <% end %>
                        </div>
                    </div>
                  </li>
                  <div class="espace"></div>
                <% end %>
            <% end %>
      <% else %>
          No comments
      <% end %>
    </ul>
    <%#= will_paginate @video_clip_comments %>
  </div>
</div>

app/views/video_clips/_video_clips.html.erb
<div class="containerLine">
  <% @video_clips.each do |video_clip| %>
      <% if video_clip.is_available? || current_person.type == 'Admin' || current_person_is_video_owner?(video_clip) %>
          <ul class="containervideo">
            <li class="videoitem">
              <div class="imagevideo">
                <% link = nil %>
                <% video_clip.thumbnails.each do |thumbnail|%>
                    <% if thumbnail.main_thumbnail == true %>
                        <% link = thumbnail.image.url(:thumb) %>
                        <% break %>
                    <% end %>
                <% end  %>

                <%= link_to( image_tag( link,
                                        title: video_clip.title,
                                        alt:   video_clip.title,
                                        size:  '175x98'), :action => 'show', :id => video_clip)
                %>

              </div>

              <div class="containerTitle">
                <div class="title">
                  <%= link_to(video_clip.title, video_clip) %>
                </div>

                <div class="titlecontainer">
                  <div>
                    By: <% @owner = Person.find_by_id(video_clip.person_id) %> <%= @owner.lastname.upcase %> <%= @owner.firstname %>
                  </div>
                  <div>
                    Views: <%= video_clip.views %>
                  </div>
                </div>

                <% if current_person.type == 'Admin' || current_person_is_video_owner?(video_clip) %>
                    <div class="adminAction">
                      <%= link_to 'Edit', edit_video_clip_path(video_clip) %>
                      <%= link_to 'Destroy', video_clip, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                <% end %>
              </div>
            </li>
          </ul>
      <% end %>
  <% end %>
</div>
<%= will_paginate @video_clips %>

app/views/video_clips/_video_clips_unavailable.html.erb
<div class="containerLine">
  <% @video_clips_unavailable.each do |video_clip| %>
      <% if !(video_clip.is_available?) && current_person.type == 'Admin'  %>
          <ul class="containervideo">
            <li class="videoitem">
              <div class="imagevideo">
                <% link = nil %>
                <% video_clip.thumbnails.each do |thumbnail|%>
                    <% if thumbnail.main_thumbnail == true %>
                        <% link = thumbnail.image.url(:thumb) %>
                        <% break %>
                    <% end %>
                <% end  %>

                <%= link_to( image_tag( link,
                                        title: video_clip.title,
                                        alt:   video_clip.title,
                                        size:  '175x98'), video_clip)
                %>
              </div>

              <div class="containerTitle">
                <div class="title">
                  <%= link_to(video_clip.title, video_clip) %>
                </div>

                <div class="titlecontainer">
                  <div>
                    By: <% @owner = Person.find_by_id(video_clip.person_id) %> <%= @owner.lastname.upcase %> <%= @owner.firstname %>
                  </div>
                  <div>
                    Views: <%= video_clip.views %>
                  </div>
                </div>

                <div class="adminAction">
                  <%= link_to 'Edit', edit_video_clip_path(video_clip) %>
                  <%= link_to 'Destroy', video_clip, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </li>
          </ul>
      <% end %>
  <% end %>
</div>
<%= will_paginate @video_clips_unavailable %>

app/views/video_clips/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Edit Video <small>Editing video</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Editing video </li>
      </ol>
    </div>
  </div>

    <%= render 'form' %>

    <%= link_to 'Show', @video_clip, class:'btn btn-default' %>
    <%= link_to 'Back', video_clips_path, class:'btn btn-default' %>
</div>

app/views/video_clips/edit.js.erb
alert(' A A A ')

app/views/video_clips/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Myvideos  <small>List videos</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Myvideos </li>
      </ol>
    </div>
  </div>

  <%= form_tag video_clips_path, :method => 'get', :id => 'video_clips_search' do %>
      <p>
        <%= text_field_tag :search_video, params[:search_video] %>
        <%= submit_tag "Search", :title => nil %>
      </p>
      <div id="video_clips_div"><%= render 'video_clips' %></div>
  <% end %>
</div>

app/views/video_clips/index.js.erb
$("#video_clips_div").html("<%= escape_javascript(render("video_clips")) %>");

app/views/video_clips/indexUnavailable.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Videos unavailable  <small>List videos</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Video unavailables </li>
      </ol>
    </div>
  </div>

  <%= form_tag video_clips_unavailables_path, :method => 'get', :id => 'video_clips_unavailable_search' do %>
      <p>
        <%= text_field_tag :search_video_unavailable, params[:search_video_unavailable] %>
        <%= submit_tag "Search", :title => nil %>
      </p>
      <div id="video_clips_unavailable_div">  <%= render 'video_clips_unavailable' %></div>
  <% end %>

</div>

app/views/video_clips/indexUnavailable.js.erb
$("#video_clips_unavailable_div").html("<%= escape_javascript(render("video_clips_unavailable")) %>");

app/views/video_clips/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Upload Video <small>Upload Video</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Upload Video </li>
      </ol>
    </div>
  </div>

    <%= render 'form' %>
    <%= link_to 'Back', video_clips_path, class:'btn btn-default' %>
</div>

app/views/video_clips/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Show Video <small>Show Video</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Show Video </li>
      </ol>
    </div>
  </div>

  <% height = 387%>
  <% width = 640 %>

  <div class="page">
    <div class="video">
      <div class="header>">
        <div class="headerTitle">
          <strong>Title: </strong>
          <%= @video_clip.title %>
        </div>
        <% if current_person.type == 'Admin' || current_person_is_video_owner?(@video_clip) %>
            <div class="headerEdit">
              <%= link_to 'Edit Video', edit_video_clip_path(@video_clip) %>
            </div>
        <% end %>
      </div>

      <!--
      <div class="videocontainer">
        <div class="player">
          <%#= video_tag([@video_clip.pathvideo], :size => '640x387', :controls => true, :preload => 'none', :autoplay => true) do%>
              Your browser does not support the video tag.
          <%# end %>
        </div>
      </div>
      -->
      <div class="videocontainer">
        <div class="player">
            <%= jwplayer({ height: height,
                           width: width,
                           file: @file_video,
                           image: @thumb_main.image.url(:original),
                           title: @video_clip.title
                         })
            %>
        </div>
      </div>

      <div class="content">
        <div class="contentInfo">

          <div class="description">
            <p>
              <strong>Description:</strong>
              <%= @video_clip.description %>
            </p>
            <p>
              <strong>Uploaded on:</strong>
              <%= @video_clip.date %>
            </p>
            <p>
              <strong>Views:</strong>
              <%= @video_clip.views %>
            </p>

            <p>
              <strong>Owner:</strong>
              <i><%= @owner.lastname.upcase %></i>
              <%= @owner.firstname %>
            </p>
          </div>

          <div class="options">
            <% Right.all.each do |right| %>
                <% if right.name != 'Comment' && right.name != 'Upload'%>
                    <al>
                      <% if right_in_current_person_personalgroup?(right.name) %>
                          <% if right.name == 'Download' %>
                              <%= link_to right.name, download_video_clip_path(@video_clip), :alt => right.name %> |
                          <% else %>
                              <%= link_to right.name, '#', :alt => right.name %> |
                          <% end %>
                      <% else %>
                          <% if current_person_groups_enable? %>
                              <% if right_in_current_person_groups?(right.name) %>
                                  <% if right.name == 'Download' %>
                                      <%= link_to right.name, download_video_clip_path(@video_clip), :alt => right.name %> |
                                  <% else %>
                                      <%= link_to right.name, '#', :alt => right.name %> |
                                  <% end %>
                              <% end %>
                          <% end %>
                      <% end %>
                    </al>
                <% end %>
            <% end %>
          </div>
        </div>

        <div id="new_comment_form_div">
            <% if right_in_current_person_personalgroup?('Comment') %>
                <p>
                  <%= form_for([@video_clip, @new_comment], :url => video_clip_comments_path(@video_clip, @new_comment), :html => { :id => 'new_comment_form'} ) do |f| %>
                      <%= f.text_field :message, size:'89x3', class:'form-control' , id:'txt', placeholder:'Comment'%><br>
                      <%= f.submit 'Post Comment', class:'btn btn-default' %>
                  <% end %>
                </p>
            <% else %>
                <% if current_person_groups_enable? %>
                    <% if right_in_current_person_groups?('Comment') %>
                        <p>
                          <%= form_for([@video_clip, @new_comment], :url => video_clip_comments_path(@video_clip, @new_comment), :html => {:id => 'new_comment_form'}) do |f| %>
                              <%= f.text_field :message, size:'89x3', class:'form-control', id:'txt' , placeholder:'Comment'%><br>
                              <%= f.submit 'Post Comment', class:'btn btn-default' %>
                          <% end %>
                        </p>
                    <% end %>
                <% end %>
            <% end %>
        </div>

        <div id="comments_div"> <%= render 'comments'  %> </div>

      </div>
    </div>
  </div>
</div>



  <!--

<p>
  <strong>Title:</strong>
  <%#= @video_clip.title %>
</p>

<p>
  <strong>Description:</strong>
  <%#= @video_clip.description %>
</p>

<p>
  <strong>Is available:</strong>
  <%#= @video_clip.is_available %>
</p>

<p>
  <strong>Date:</strong>
  <%#= @video_clip.date %>
</p>

<p>
  <strong>Views:</strong>
  <%#= @video_clip.views %>
</p>

<p>
  <%#= jwplayer({ height: height,
                 width: width,
                 file: @video_clip.videoitemclip.url,
                 image: '',
                 title: @video_clip.title
               })
  %>
</p>

<p>
  <%#= link_to "Download", @video_clip.videoitemclip.url(:original, false) %>
  <%#= link_to 'Download', download_video_clip_path(@video_clip) %>  OK
  <%#= link_to 'Download', download_url_video_clip_path(@video_clip) %>
</p>
 -->

</div>